### ISSUE TITLE
merchandise.java

### ISSUE THREAD

**Issue by ragcode7** [manavpatnaik/java_oop_project#5]
`

    public class Merchandise extends Organiser {
       private int item_id;
       private String item_name;
       private double item_cost;
       private int quantity;
       private String shipper;
       private double mtotal;

    mtotal=0.0;

    public Merchandise(int organiserId, int item_id,String item_name,int item_cost,int quantity, String shipper ){
      super(organiserId);
      this.item_id=item_id;
      this.item_cost=item_cost;
      this.item_name=item_name;
      this.quantity=quantity;
      this.shipper= shipper;
    }

    public int getitem_id(){
      return item_id;
    }

    public void setitem_id(int item_id){
      this.item_id = item_id;
    }

    public String getitem_name(){
      return item_name;
    }

    public void setitem_name(String item_name){
      this.item_name=item_name;
    }

    public double getitem_cost(){
      return item_cost;
    }

    public void setitem_cost(double item_cost){
      this.item_cost=item_cost;
    }

    public int getQuantity(){
      return quantity;
    }

    public void setQuantity(int quantity){
      this.quantity=quantity;
    }

    public String getShipper(){
      return shipper;
    }

    public void setShipper(String shipper){
      this.shipper=shipper;
    }

    public void calcTotal(double item_cost, int quantity){
      mtotal = item_Cost*quantity;
    }

    public String toString(){
      return "Item id       : " + Integer.toString(this.item_id) + "\n" +
             "Item name     : " + this.item_name + "\n" +
             "Item cost     : " + this.item_cost + "\n" +
             "Item quantity : " + this.quantity + "\n" +
             "Item shipper  : " + this.shipper + "\n" +
             "Total         : " + mtotal + "\n" ;
    }
    }
`

**Comment by manavpatnaik** [comment]
OK done.
