### ISSUE TITLE
advertisement.java

### ISSUE THREAD

**Issue by ragcode7** [manavpatnaik/java_oop_project#6]
`      
        public class Advertisement extends Organiser{
            private int ad_id;
            private String ad_title;
            private String ad_type; //say we have 2/ options - basic and premium
            private String ad_duration;

    public Advertisement(int organiserId, int ad_id, String ad_title, String ad_type , String ad_duration){
      super(organiserId);
      this.ad_id= ad_id;
      this.ad_title=ad_title;
      this.ad_type=ad_type;
      this.ad_duration=ad_duration;
    }

    public int getad_id(){
      return ad_id;
    }

    public void setad_id(ad_id){
      this.ad_id=ad_id;
    }

    public String getad_title(){
      return ad_title;
    }

    public void setad_title(ad_title){
      this.ad_title=ad_title;
    }

    public String getad_type(){
      return ad_type;
    }

    public void setad_type(ad_type){
      this.ad_type=ad_type;
    }

    public String getad_duration(){
      return ad_duration;
    }

    public void setad_duration(ad_duration){
      this.ad_duration=ad_duration;
    }

    public String toString(){
      return "Advertisement ID      : " + Integer.toString(this.ad_id)  + "\n" +
             "Advertisement Title   : " + this.ad_title + "\n" +
             "Advertisement Type    : " + this.ad_type + "\n" +
             "Advertisement Duration: " + this.ad_duration + "\n" ;
    }
    }
`

**Comment by manavpatnaik** [comment]
Having the organizer as a data field is more appropriate than inheriting. If we inherit, it becomes an IS-A relationship. But advertisement IS-NOT an Organizer. Will change that alone
